IInterface/Controllers/SubActionPlanTimeController.cs
using IInterface.Business;
using IInterface.Common;
using IInterface.Common.CommonBO;
using IInterface.Filter;
using IInterface.Models;
using IModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IInterface.Controllers
{
    public class SubActionPlanTimeController : Controller
    {
        private Entities Context = new Entities();
        private ObjectRoleBO GetRole(Plan plan)
        {
            var user = SessionManager.GetUserInfo();
            ObjectRoleBO role = null;
            ChangeRequest cr = plan.Status == Constants.PLAN_APPROVED ?
                Context.ChangeRequest.Where(x => x.PlanID == plan.PlanID && x.IsFinish == null).OrderByDescending(x => x.ChangeRequestID).FirstOrDefault() : null;
            if (cr != null)
            {
                role = new FlowProcessBusiness(Context).GetRoleForPlanChange(user.UserID, plan.PlanID);
            }
            else
            {
                role = new FlowProcessBusiness(Context).GetRoleForObject(user.UserID, plan.PlanID, Constants.COMMENT_TYPE_PLAN_TARGET);
            }
            return role;
        }
        // GET: SubPlanActionTime
        int userID = SessionManager.GetUserInfo().UserID;
        DateTime now = DateTime.Now;
        [BreadCrumb(ControllerName = "Thời gian thực hiện", ActionName = "Thời gian thực hiện", AreaName = "Kế hoạch")]
        public ActionResult Index(int planID)
        {
            // Plan plan = Context.Plan.Find(PlanID);
            Plan plan = Context.Plan.Where(x => x.PlanID == planID).FirstOrDefault();
            if (plan != null)
            {
                Period period = Context.Period.Find(plan.PeriodID);
                int startYear = period.FromDate.Year;
                int finishYear = period.ToDate.Year;
                int rangeYear = finishYear - startYear;
                ViewData["Dept"] = Context.Department.Find(plan.DepartmentID);
                ViewData["Plan"] = plan;
                ViewData["Period"] = period;
                //     ViewData["StartYear"] = startYear;
                ViewData["RangeYear"] = rangeYear;

                List<PlanTargetModel> lstPlanTarget = GetPlanTargetByPlan(plan.PlanID);
                ViewData["PlanTarget"] = lstPlanTarget;
                List<ChangeRequestActionModel> listChangeAction;
                if (plan.IsChange.GetValueOrDefault() == 0)
                {
                    listChangeAction = new PlanBusiness(Context).GetPlanUnlockAction(plan.PlanID);
                }
                else
                {
                    listChangeAction = new PlanBusiness(Context).GetRequestAction(plan.PlanID);
                }
                if (listChangeAction != null)
                {
                    ViewData["listChangeAction"] = listChangeAction;
                }
                // Role
                ObjectRoleBO role = GetRole(plan);
                if (role == null || role.Role == Constants.ROLE_NO_VIEW)
                {
                    return RedirectToAction("RoleErrorBusiness", "Home");
                }
                ViewData["role"] = role;

            }
            else
            {
                ViewBag.ErrorContent = "Kế hoạch chưa được lập, vui lòng tạo kế hoạch với thông tin chung trước";
                return RedirectToAction("RoleErrorBusiness", "Home");
            }


            return View();
        }

        public List<PlanTargetModel> GetPlanTargetByPlan(int planId)
        {
            List<PlanTargetModel> lstPlanTarget = Context.PlanTarget.Where(x => x.PlanID == planId)
                .OrderBy(x => x.TargetOrder)
                .ThenBy(x => x.PlanTargetTitle)
                .Select(x => new PlanTargetModel
                {
                    PlanTargetID = x.PlanTargetID,
                    PlanTargetContent = x.PlanTargetContent,
                    TargetID = x.TargetID,
                    PlanID = x.PlanID,
                    TargetCode = x.TargetCode,
                    DepartmentID = x.DepartmentID
                })
                .ToList();
            foreach (PlanTargetModel pt in lstPlanTarget)
            {
                List<PlanTargetActionModel> lst = GetPlanTargetAction(pt.PlanID, pt.PlanTargetID);


                foreach (PlanTargetActionModel pta in lst)
                {
                    List<SubActionPlanModel> lstSubAction = GetSubActionPlanByPlanTargetId(pta.PlanTargetActionID);
                    pta.ListSubActionPlan = lstSubAction;
                }
                pt.ListPlanTargetActionModel = lst;
            }

            return lstPlanTarget;
        }

        public List<PlanTargetActionModel> GetPlanTargetAction(int planId, int? targetId)
        {
            List<PlanTargetActionModel> lstPlanTargetAction =
                Context.PlanTargetAction.Where(x => x.PlanID == planId && x.PlanTargetID == targetId)
                .OrderBy(x => x.ActionOrder)
                .Select(x => new PlanTargetActionModel
                {
                    PlanTargetActionID = x.PlanTargetActionID,
                    ActionCode = x.ActionCode,
                    ActionContent = x.ActionContent,
                    Exucuter = x.Exucuter,
                    Supporter = x.Supporter,
                    Note = x.Note

                }).ToList();

            foreach (PlanTargetActionModel pta in lstPlanTargetAction)
            {
                List<SubActionPlanTimeModel> lstSubActionPlanTime = Context.SubActionPlanTime
                           .Where(x => x.PlanTargetActionID == pta.PlanTargetActionID && x.SubActionPlanID == null)
                           .Select(x => new SubActionPlanTimeModel
                           {
                               SubActionPlanTimeID = x.SubActionPlanTimeID,
                               PlanTargetAcionID = x.PlanTargetActionID,
                               PlanTime = x.PlanTime,
                               PlanYear = x.PlanYear,
                               Executer = x.Executer,
                               Supporter = x.Supporter,
                               Note = x.Note,
                               CreateUserID = x.CreateUserID,
                               ModifierID = x.ModifierID

                           }).ToList();
                pta.ListSubActionPlanTime = lstSubActionPlanTime;

            }

            return lstPlanTargetAction;
        }
        // Lay thong tin SubAction
        public List<SubActionPlanModel> GetSubActionPlanByPlanTargetId(int PlanTargetActionID)
        {
            List<SubActionPlanModel> lstSubActionPlan = Context.SubActionPlan.Where(x => x.PlanTargetActionID == PlanTargetActionID && x.ParentID == null)
                .OrderBy(x => x.SubActionOrder)
                .Select(x => new SubActionPlanModel
                {
                    SubActionPlanID = x.SubActionPlanID,
                    SubActionContent = x.SubActionContent,
                    PlanTargetActionID = x.PlanTargetActionID,
                    SubActionCode = x.SubActionCode,
                    Exucuter = x.Exucuter,
                    Supporter = x.Supporter,
                    Note = x.Note,
                    ParentID = x.ParentID

                }).ToList();
            foreach (SubActionPlanModel sal in lstSubActionPlan)
            {
                List<SubActionPlanTimeModel> lstSubActionPlanTime = Context.SubActionPlanTime
                           .Where(x => x.SubActionPlanID == sal.SubActionPlanID)
                           .Select(x => new SubActionPlanTimeModel
                           {
                               SubActionPlanTimeID = x.SubActionPlanTimeID,
                               SubActionPlanID = x.SubActionPlanID,
                               PlanTime = x.PlanTime,
                               CreateUserID = x.CreateUserID,
                               ModifierID = x.ModifierID

                           })
                           .ToList();
                sal.ListSubActionPlanTime = lstSubActionPlanTime;
                sal.ListChildSubActionPlan = GetListChildSubActionPlanBySubActionId(sal.SubActionPlanID.Value);
            }

            return lstSubActionPlan;
        }

        public List<SubActionPlanModel> GetListChildSubActionPlanBySubActionId(int subActionPlanId)
        {
            List<SubActionPlanModel> lstSubActionPlan = Context.SubActionPlan.Where(x => x.ParentID == subActionPlanId)
                .OrderBy(x => x.SubActionOrder)
                .Select(x => new SubActionPlanModel
                {
                    SubActionPlanID = x.SubActionPlanID,
                    SubActionContent = x.SubActionContent,
                    PlanTargetActionID = x.PlanTargetActionID,
                    SubActionCode = x.SubActionCode,
                    Exucuter = x.Exucuter,
                    Supporter = x.Supporter,
                    Note = x.Note,
                    ParentID = x.ParentID

                }).ToList();
            foreach (SubActionPlanModel sal in lstSubActionPlan)
            {
                List<SubActionPlanTimeModel> lstSubActionPlanTime = Context.SubActionPlanTime
                           .Where(x => x.SubActionPlanID == sal.SubActionPlanID)
                           .Select(x => new SubActionPlanTimeModel
                           {
                               SubActionPlanTimeID = x.SubActionPlanTimeID,
                               SubActionPlanID = x.SubActionPlanID,
                               PlanTime = x.PlanTime,
                               CreateUserID = x.CreateUserID,
                               ModifierID = x.ModifierID
                           })
                           .ToList();
                sal.ListSubActionPlanTime = lstSubActionPlanTime;
            }
            return lstSubActionPlan;
        }

IInterface/Views/SubActionPlanTime/AddSubActionPlan.cshtml
@using IInterface.Common;
@using IInterface.Models;

@model SubActionPlanModel



@using (Ajax.BeginForm("AddSubActionPlan", "SubActionPlanTime", new AjaxOptions()
{
    HttpMethod = "POST",
    OnBegin = "onBegin",
    OnSuccess = "onSuccess",
}, new { id = "frmSubAction" }))
{

           @Html.HiddenFor(x => x.PeriodID, new { id = "PeriodID" })
           @Html.HiddenFor(x => x.PlanID, new { id = "PlanID" })
           @Html.HiddenFor(x => x.PlanTargetActionID, new { id = "PlanTargetActionID" })
           @Html.HiddenFor(x => x.SubActionPlanID, new { id = "SubActionPlanID" })
           @Html.HiddenFor(x => x.PlanTargetID, new { id = "PlanTargetID" })
           @Html.HiddenFor(x => x.SumCostType, new { id = "SumCostType" })

        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="addActionID">Mã hoạt động </label>
                      @Html.TextBoxFor(x =>x.ParentPlanTagetActionCode, new {@class = "form-control", id = "ParentPlanTagetActionCode", @readonly = "readonly" })
                    
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="addActionCode">Hoạt động</label>
                    @Html.TextBoxFor(x => x.ParentPlanTagetActionContent, new { @class = "form-control", id = "ParentPlanTagetActionContent", @readonly = "readonly" })
                    
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="form-group">
                    <label for="addActionContent">Nội dung hoạt động</label>
                    @Html.TextAreaFor(x => x.SubActionContent, new { placeholder = "Nội dung hoạt động", @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="row" style="display: none">
            <div class="col-lg-12">
             
                <input type="checkbox" name="" id="chkSpendType" class="cbx" onclick="onSetValClick(this)">
                &nbsp;
                <label for="addCheck">Loại chi phí tổng hợp từ 1 mục chi </label>
            </div>
        </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-success" onclick="onSaveSubAction()">
            <i class="fa fa-save"></i>
            Lưu
        </button>
    </div>
}

<script>
    function onSaveSubAction() {
        var subActionContent = $("#frmSubAction #SubActionContent").val();
        
        if (subActionContent == null || subActionContent == "") {
            alert("Chưa nhập nội dung hoạt động");
            return false;
        }
        var myFrmData = $("#frmSubAction").serialize();
        var planID = $("#PlanID").val();
        $.ajax({
            type: "POST",
            url: '@Url.Action("AddSubActionPlan", "SubActionPlanTime")',
            data: myFrmData,
            success: function (data) {
                CommonJS.alert(data);
                $("#modal").modal("hide");
                window.location.href = "/SubActionPlanTime/Index?planID=" + planID;

            },
            error: function (e) {
                CommonJS.alert("Có lỗi hệ thống");
                // alert("Có lỗi hệ thống");

            }
        });

    }

    function onSetValClick(item) {
        if ($(item).is(':checked')) {

            $(item).attr("value", "true");
            $("#frmSubAction #SumCostType").val(1);
        } else {
            $(item).attr("value", "false");
            $("#frmSubAction #SumCostType").val('');
        }
    }
</script>

IInterface/Views/SubActionPlanTime/Index.cshtml
@using IModel;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";


    Department dept = ViewData["Dept"] as Department;
    Period period = ViewData["Period"] as Period;

}


<script type="text/javascript" src="~/Scripts/jquery.freezeheader.js" ></script>

<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-body">
                <div class="box-header">
                    <h3 class="box-title">
                        <i class="fa fa-calendar-check-o"></i> Thời gian thực hiện đơn vị @dept.DepartmentName.Replace("đơn vị", string.Empty).Replace("Đơn vị", string.Empty) - @period.PeriodName
                    </h3>
                </div>
                <div style="display: none">

                    @using (Ajax.BeginForm("GetListSubActionPlanTime", "SubActionPlanTime", new AjaxOptions
                {
                    HttpMethod = "get",
                    UpdateTargetId = "divGridSubActionPlan"
                }, new { id = "frmSearch" }))
                {
                
                }
                </div>
                </div>
                <div class="box-body">
                    <div class="row">
                        <div class="col-lg-12" id="divGridSubActionPlan">
                       
                            @Html.Partial("_ListSubActionPlanTime")
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
      
      
        $("#tableData").freezeHeader();
       
    });

    function onSearch() {

        var SubActionContent = $("#SubActionContent").val();
        $.ajax({
            type: "POST",
            //   url: "/SubActionPlanTime/UpdateSubActionPlanTime?subTargetId=" + ,
            url: '@Url.Action("GetListSubActionPlanTime", "SubActionPlanTime")',
            data: { periodId: @period.PeriodID,subActionContent: SubActionContent  },
          
            success: function (data) {

            //    CommonJS.alert(data);
                //  searchMemberForGroup();

                //    searchMember();

            },
            error: function (e) {
                CommonJS.alert("Có lỗi hệ thống");
            }
        });

      //  $("#frmSearch").submit();
    }

</script>
  