IInterface/Controllers/CostEstimateController.cs
using IInterface.Business;
using IInterface.Common;
using IInterface.Filter;
using IInterface.Models;
using IModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IInterface.Controllers
{
    public class CostEstimateController : Controller
    {
        // GET: Action
        private Entities context = new Entities();

        [BreadCrumb(ControllerName = "Dự toán quỹ", ActionName = "Dự toán quỹ", AreaName = "Kế hoạch")]
        public ActionResult Index(int periodId, int isView = 0)
        {
            Period period = context.Period.Where(x => x.PeriodID == periodId).FirstOrDefault();
            if (period != null)
            {
                ViewData["Period"] = period;

                Plan plan = context.Plan.Where(x => x.PeriodID == periodId && x.DepartmentID == Constants.HEAD_DEPT_ID).FirstOrDefault();
                if (plan == null)
                {
                    throw new BusinessException("Không tồn tại kế hoạch, vui lòng kiểm tra lại");
                }
                ViewData["Plan"] = plan;
                if (plan != null)
                {
                    CostEstimateBusiness bus = new CostEstimateBusiness(this.context);
                    if (isView == 0)
                    {
                        bus.Init(plan.PlanID);
                        context.SaveChanges();
                    }
                    List<PlanTargetModel> lstPlanTarget = bus.GetListPlanTargetCost(plan.PlanID);
                    // Lay them thong tin ve chi phi tong hop tu don vi
                    ViewData["PlanTarget"] = lstPlanTarget;
                    List<CostEstimateSpendModel> listCostSpend = bus.GetListRootSpend(plan.PlanID);
                    ViewData["listSpend "] = listCostSpend;
                }
                else
                {
                    throw new BusinessException("Không tồn tại kế hoạch, vui lòng kiểm tra lại");
                }
            }
            return View();
        }

        public PartialViewResult SyncCostEstimate(int periodID)
        {
            Period period = context.Period.Where(x => x.PeriodID == periodID).FirstOrDefault();
            if (period != null)
            {
                ViewData["Period"] = period;

                Plan plan = context.Plan.Where(x => x.PeriodID == periodID && x.DepartmentID == Constants.HEAD_DEPT_ID).FirstOrDefault();
                if (plan != null)
                {
                    CostEstimateBusiness bus = new CostEstimateBusiness(this.context);
                    List<PlanTargetModel> lstPlanTarget = bus.GetListPlanTargetCost(plan.PlanID, true);
                    // Lay them thong tin ve chi phi tong hop tu don vi
                    ViewData["PlanTarget"] = lstPlanTarget;
                    List<CostEstimateSpendModel> listCostSpend = bus.GetListRootSpend(plan.PlanID);
                    ViewData["listSpend "] = listCostSpend;
                }
                else
                {
                    throw new BusinessException("Không tồn tại kế hoạch, vui lòng kiểm tra lại");
                }
            }
            else
            {
                throw new BusinessException("Không tồn tại giai đoạn, vui lòng kiểm tra lại");
            }
            return PartialView("_ListEstimateCost");
        }

        public JsonResult DelSpendItem(int id)
        {
            CostEstimateBusiness bus = new CostEstimateBusiness(this.context);
            bus.DelSpendCost(id);
            return Json(new { Type = "SUCCESS", Message = "Xóa hạng mục chi thành công" }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SaveCostEstimate(List<string> TotalPrice, List<long> SubCostID, List<string> ArrDesc, int periodId)
        {
            Plan plan = this.context.Plan.Where(x => x.PeriodID == periodId && x.Status != Constants.IS_NOT_ACTIVE && x.DepartmentID == Constants.HEAD_DEPT_ID).FirstOrDefault();
            if (plan == null)
            {
                throw new BusinessException("Kế hoạch chưa được lập, vui lòng kiểm tra lại");
            }
            CostEstimateBusiness bus = new CostEstimateBusiness(this.context);
            bus.SaveCostEstimate(TotalPrice, SubCostID, ArrDesc, plan.PlanID);
            context.SaveChanges();
            return Json(new { Type = "SUCCESS", Message = "Cập nhật thông tin dự toán quỹ thành công" });

        }

        public PartialViewResult AddSpendItem(int planID, int? id, string type, string[] spendCodes, string[] spendContents)
        {
            Plan plan = context.Plan.Find(planID);
            if (plan == null)
            {
                throw new BusinessException("Không tồn tại kế hoạch đã chọn");
            }
            Period period = context.Period.Find(plan.PeriodID);
            if (period == null)
            {
                throw new BusinessException("Dữ liệu không hợp lệ");
            }
            int userID = SessionManager.GetUserInfo().UserID;
            int? planTargetID = null;
            int? planTargetActionID = null;
            int? subActionPlanID = null;
            int? parentID = null;
            int? MainActionID = null;
            if ("targetaction".Equals(type))
            {
                PlanTargetAction pta = this.context.PlanTargetAction.Find(id);
                if (pta == null)
                {
                    throw new BusinessException("Dữ liệu không hợp lệ");
                }
                planTargetActionID = pta.PlanTargetActionID;
                planTargetID = pta.PlanTargetID.Value;
                MainActionID = pta.MainActionID.Value;
            }
            else if ("subaction".Equals(type))
            {
                var subAction = (from s in this.context.SubActionPlan
                                 join p in this.context.PlanTargetAction on s.PlanTargetActionID equals p.PlanTargetActionID
                                 select new
                                 {
                                     p.PlanTargetID,
                                     p.PlanTargetActionID,
                                     s.SubActionPlanID,
                                     s.SubActionID
                                 }).FirstOrDefault();
                if (subAction == null)
                {
                    throw new BusinessException("Dữ liệu không hợp lệ");
                }
                planTargetActionID = subAction.PlanTargetActionID;
                subActionPlanID = subAction.SubActionPlanID;
                planTargetID = subAction.PlanTargetID.Value;
                MainActionID = subAction.SubActionID.Value;
            }
            else if ("subcost".Equals(type))
            {
                CostEstimateSpend subItem = this.context.CostEstimateSpend.Find(id);
                if (subItem == null)
                {
                    throw new BusinessException("Dữ liệu không hợp lệ");
                }
                PlanTargetAction pta = this.context.PlanTargetAction.Find(subItem.PlanTargetActionID);
                if (pta == null)
                {
                    throw new BusinessException("Dữ liệu không hợp lệ");
                }
                planTargetActionID = pta.PlanTargetActionID;
                subActionPlanID = subItem.SubActionPlanID;
                planTargetID = pta.PlanTargetID.Value;
                MainActionID = subItem.MainActionID;
                parentID = id;
            }
            // Luu muc chi cao nhat lam cha
            int startIdx = 0;
            List<CostEstimateSpend> listSubSpendItem = new List<CostEstimateSpend>();
            List<CostEstimateSpendModel> listModel = new List<CostEstimateSpendModel>();
            for (int i = startIdx; i < spendContents.Length; i++)
            {
                CostEstimateSpend spendItem = new CostEstimateSpend();
                spendItem.PlanTargetID = planTargetID;
                spendItem.ParentID = parentID;
                spendItem.PlanTargetActionID = planTargetActionID;
                spendItem.SpendContent = spendContents[i];
                spendItem.SpendItemTitle = spendCodes[i];
                spendItem.SubActionPlanID = subActionPlanID;
                spendItem.MainActionID = MainActionID;
                spendItem.PlanID = planID;
                this.context.CostEstimateSpend.Add(spendItem);
                listSubSpendItem.Add(spendItem);
            }
            context.SaveChanges();
            // Insert phan cost
            int fromYear = period.FromDate.Year;
            int toYear = period.ToDate.Year;
            List<CostEstimateDetail> listCost = new List<CostEstimateDetail>();
            for (int year = fromYear; year <= toYear; year++)
            {
                foreach (CostEstimateSpend item in listSubSpendItem)
                {
                    CostEstimateDetail cost = new CostEstimateDetail();
                    cost.PlanTargetActionID = planTargetActionID;
                    cost.PlanTargetID = planTargetID.Value;
                    cost.PlanYear = year;
                    cost.SubActionPlanID = subActionPlanID;
                    cost.MainActionID = item.MainActionID;
                    cost.CostEstimateSpendID = item.CostEstimateSpendID;
                    cost.PlanID = planID;
                    this.context.CostEstimateDetail.Add(cost);
                    listCost.Add(cost);
                }
            }
            context.SaveChanges();
            for (int i = 0; i < listSubSpendItem.Count; i++)
            {
                CostEstimateSpendModel model = new CostEstimateSpendModel();
                model.CostEstimateSpendID = listSubSpendItem[i].CostEstimateSpendID;
                model.SpendContent = listSubSpendItem[i].SpendContent;
                model.SpendItemTitle = listSubSpendItem[i].SpendItemTitle;
                model.SubActionPlanID = subActionPlanID;

IInterface/Views/CostEstimate/Index.cshtml
@using IModel;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";


    Period period = ViewData["Period"] as Period;    
    int fromYear = period.FromDate.Year;
    int toYear = period.ToDate.Year;
    string title = "KẾ HOẠCH HOẠT ĐỘNG VÀ KINH PHÍ GIAI ĐOẠN " + fromYear + "-" + toYear;
}
<script type="text/javascript" src="~/Scripts/jquery.freezeheader.js"></script>

<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-body">
                <div class="box-header">
                    <h4 class="box-title">
                        QUỸ PHÒNG CHỐNG TÁC HẠI CỦA THUỐC LÁ
                    </h4>
                    <br />
                    <h4 class="text-center">
                         @title
                    </h4>
                </div>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-lg-12" id="divGridSubActionPlan">
                        @Html.Partial("_ListEstimateCost")
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="modalSpendItem" class="modal fade" role="dialog">
    @Html.Partial("_AddSpendItem")
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#tableData").freezeHeader();
    });
    function onSuccess(msg) {
        CommonJS.alert(msg);
    }

    function onFail(xhr) {
        CommonJS.alert(xhr.responseText);
    }
</script>
<style type="text/css">
    .text-only-view {
        background-color: transparent !important;
        border: 0 !important;
        background: transparent !important;
    }
</style>

IInterface/Views/CostEstimate/_AddSpendItem.cshtml
@using IModel;
@{
    Plan plan = ViewData["Plan"] as Plan;
}
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        @using (Ajax.BeginForm("AddSpendItem", "CostEstimate", new AjaxOptions()
        {
            HttpMethod = "POST",
            OnFailure = "onFail",
            OnSuccess = "onAddSpendSuccess",
        }, new { id = "frmSpendItem" }))
        {
            <div class="modal-header">
                <input type="hidden" name="planID" id="planID" value="@plan.PlanID" />
                <input type="hidden" id="idpar" />
                <input type="hidden" name="id" id="id" />
                <input type="hidden" name="type" id="type" />
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="titleSpend"></h4>
            </div>
            <div class="modal-body">
                <div class="row" style="padding-top: 5px;">
                    <div class="col-md-12">
                        <button type="button" class="btn btn-success pull-right" onclick="addSpendItem()">
                            <i class="fa fa-plus"></i>
                            Thêm mục chi
                        </button>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-bordered" id="tblSpendItem">
                            <thead>
                                <tr>
                                    <th style="text-align: center; vertical-align: middle; width: 15%;">
                                        Mã mục chi
                                    </th>
                                    <th style="text-align: center; vertical-align: middle; width: 75%;">
                                        Tên mục chi
                                    </th>
                                    <th style="text-align: center; vertical-align: middle; width: 10%;">
                                    </th>
                                </tr>
                            </thead>
                            <tbody></tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" data-dismiss="modal" class="btn btn-default"><i class="fa fa-ban"></i> Hủy</button>
                <button type="submit" class="btn btn-success">
                    <i class="fa fa-save"></i>
                    Lưu
                </button>
            </div>
        }
    </div>
</div>
<script type="text/javascript">
    function addSpendItem() {
        var markup = "<tr><td style='width: 15%;'><input type='text' name='spendCodes' class='form-control' /></td>" +
            "<td style='width: 75%;'><input type='text' name='spendContents' class='form-control' /></td>" +
            "<td style='text-align:center'><button type='button' class='btn btn-danger' title='Xóa mục chi' onclick='removeSpendItem(this)'><i class='fa fa-trash-o'></i></button></td></tr>";
        $("#tblSpendItem tbody").append(markup);
    }

    function removeSpendItem(item) {
        console.log($(item).closest('tr'));
        var tr = $(item).closest('tr');
        tr.remove();
    }

    function findLastChild(tr) {
        var id = tr.attr('id');
        var countChild = 0;
        var lastChild;
        $('table tr[parentid="' + id + '"]').each(function () {
            countChild++;
            lastChild = $(this);
        });
        if (countChild == 0) {
            return tr;
        } else {
            return findLastChild(lastChild);
        }
    }

    function onAddSpendSuccess(data) {
        CommonJS.alert("Thêm hạng mục chi thành công");
        var id = $('#frmSpendItem #idpar').val();
        if (id == '') {
            $("#tableData tbody").append(data);
        } else {
            var tr = findLastChild($('#' + id));
            tr.after(data);
        }
    }
</script>

IInterface/Views/CostEstimate/_ListPlanTargetAction.cshtml
@using IInterface.Models;
@using IModel;
@model PlanTargetActionModel
@{
    string parentID = "target_" + Model.PlanTargetID;
    Period period = ViewData["Period"] as Period;
    int startYear = period.FromDate != null ? period.FromDate.Year : 0;
    int endYear = period.ToDate != null ? period.ToDate.Year : 0;
    int rangeYear = endYear - startYear;
    bool hasChild = false;
    if((Model.ListSubActionPlan != null && Model.ListSubActionPlan.Any())
        || (Model.ListCostEstimateSpend != null && Model.ListCostEstimateSpend.Any()))
    {
        hasChild = true;
    }
    string des = string.Empty;
}

<tr id="targetaction_@Model.PlanTargetActionID" parentid="target_@Model.PlanTargetID">
    @if (Model.ListSubActionPlan == null || Model.ListSubActionPlan.Count == 0)
    {
        <td style="text-align:center; vertical-align: middle">
            <a title="Thêm mục chi" href="javascript:void(0)" onclick="openAddSpendItem('@Model.PlanTargetActionID', '@Model.ActionContent','targetaction', 'targetaction_@Model.PlanTargetActionID')">
                <span class="fa fa-plus-square"></span>
            </a>
            <b>@Model.ActionCode</b>
        </td>
    }
    else
    {
        <td style="text-align:center; vertical-align: middle">
            <b> @Model.ActionCode </b>
        </td>
    }
    <td style="vertical-align: middle">
        <b>@Model.ActionContent</b>
    </td>
    @for (int i = 0; i <= rangeYear; i++)
    {
        int year = i + startYear;
        CostEstimateDetailModel cost = Model.ListCostEstimateDetail == null ? null : Model.ListCostEstimateDetail.Where(x => x.PlanYear == year).FirstOrDefault();
        if(cost != null)
        {
            cost.HasChild = hasChild;
            des = cost.Description;
        }
        @Html.Partial("_ListYearCost", cost);
    }
    <td style="text-align:center; vertical-align:middle">
        <input type="text" class="currency form-control input-sm text-only-view" name="SumTotalBudget" readonly="readonly" value="@Model.TotalBudget" style="text-align:right">
    </td>
    <td style="text-align:center; vertical-align:middle">
        <textarea stystyle="text-align:right;" name="ArrDesc" class="form-control input-sm">@des</textarea>
    </td>
</tr>
@if (Model.ListSubActionPlan != null && Model.ListSubActionPlan.Any())
{
    int idxSubAction = 1;
    foreach (SubActionPlanModel item in Model.ListSubActionPlan)
    {
        item.SubActionCode = Model.ActionCode + "." + idxSubAction;
        idxSubAction++;
        @Html.Partial("_ListSubAction", item);
    }
}
else
{
    if (Model.ListCostEstimateSpend != null && Model.ListCostEstimateSpend.Any())
    {
        int idxSubCost = 1;
        foreach (CostEstimateSpendModel item in Model.ListCostEstimateSpend)
        {
            item.SpendItemTitle = Model.ActionCode + "." + idxSubCost;
            idxSubCost++;
            @Html.Partial("_ListSubCost", item);
        }
    }
}

IInterface/Views/CostEstimate/_ListSubAction.cshtml
@using IInterface.Models;
@using IModel;
@model SubActionPlanModel
@{
    Period period = ViewData["Period"] as Period;
    int rangeYear = (int)ViewData["RangeYear"];

    int startYear = period.FromDate != null ? period.FromDate.Year : 0;
    int endYear = period.ToDate != null ? period.ToDate.Year : 0;
    string parentid = Model.ParentID != null ? "subaction_" + Model.ParentID.Value : "targetaction_" + Model.PlanTargetActionID.GetValueOrDefault();
    bool hasChild = false;
    if ((Model.ListChildSubActionPlan != null && Model.ListChildSubActionPlan.Any())
        || (Model.ListCostEstimateSpend != null && Model.ListCostEstimateSpend.Any()))
    {
        hasChild = true;
    }
    string des = string.Empty;
}

<tr id="subaction_@Model.SubActionPlanID" parentid="@parentid">
    @if (Model.ListChildSubActionPlan == null || Model.ListChildSubActionPlan.Count == 0)
    {
        <td style="text-align:center; vertical-align: middle">
            <a title="Thêm mục chi" href="javascript:void(0)" onclick="openAddSpendItem('@Model.SubActionPlanID', '@Model.SubActionContent','subaction', 'subaction_@Model.SubActionPlanID')">
                <span class="fa fa-plus-square"></span>
            </a>
            @Model.SubActionCode
        </td>
    }
    else
    {
        <td style="text-align:center; vertical-align: middle">
            @Model.SubActionCode
        </td>
    }
    <td style="vertical-align:middle">
        @Model.SubActionContent
    </td>
    @for (int i = 0; i <= rangeYear; i++)
    {
        int year = i + startYear;
        CostEstimateDetailModel cost = Model.ListCostEstimateDetail == null ? null : Model.ListCostEstimateDetail.Where(x => x.PlanYear == year).FirstOrDefault();
        if (cost != null)
        {
            des = cost.Description;
            cost.HasChild = hasChild;
        }
        @Html.Partial("_ListYearCost", cost);
    }
    <td style="text-align:center; vertical-align:middle">
        <input type="text" class="currency form-control input-sm text-only-view" name="SumTotalBudget" readonly="readonly" value="@Model.TotalBudget" style="text-align:right">
    </td>
    <td style="text-align:center; vertical-align:middle">
        <textarea stystyle="text-align:right;" name="ArrDesc" class="form-control input-sm">@des</textarea>
    </td>
</tr>
@if (Model.ListChildSubActionPlan != null && Model.ListChildSubActionPlan.Any())
{
    foreach (SubActionPlanModel item in Model.ListChildSubActionPlan)
    {
        @Html.Partial("_ListSubAction", item);
    }
}
else
{
    if (Model.ListCostEstimateSpend != null && Model.ListCostEstimateSpend.Any())
    {
        foreach (CostEstimateSpendModel item in Model.ListCostEstimateSpend)
        {
            @Html.Partial("_ListSubCost", item);
        }
    }
}

IInterface/Views/CostEstimate/_ListSubCost.cshtml
@using IInterface.Models;
@using IInterface.Common;
@using IModel;
@model CostEstimateSpendModel
@{
    Period period = ViewData["Period"] as Period;

    int startYear = period.FromDate != null ? period.FromDate.Year : 0;
    int endYear = period.ToDate != null ? period.ToDate.Year : 0;
    string parentid = Model.ParentID != null ? "subcost_" + Model.ParentID.Value :
        (Model.SubActionPlanID != null ? "subaction_" + Model.SubActionPlanID.Value :
        (Model.PlanTargetActionID != null ? "targetaction_" + Model.PlanTargetActionID.Value : 
        (Model.PlanTargetID != null ? "target_" + Model.PlanTargetID.Value : "sumall")));
    string des = string.Empty;
    string classTr = "";
    if (string.IsNullOrWhiteSpace(parentid))
    {
        classTr = "success";
    }
}

<tr class="@classTr" id="subcost_@Model.CostEstimateSpendID" parentid="@parentid">
    <td style="text-align:center; vertical-align:middle">
        @if (Model.IsSalary.GetValueOrDefault() == Constants.IS_ACTIVE && Model.SalaryType != null)
        {
            <a title="Tổng hợp lại" href="javascript:void(0)" onclick="syncSalary('@Model.CostEstimateSpendID')">
                <span class="fa fa-recycle"></span>
            </a>
        }
        else
        {
            <a title="Xóa mục chi" href="javascript:void(0)" onclick="delSpendItem(@Model.CostEstimateSpendID)">
                <span class="fa fa-trash-o text-danger"></span>
            </a>
            <a title="Thêm mục chi" href="javascript:void(0)" onclick="openAddSpendItem('@Model.CostEstimateSpendID', '@Model.SpendContent', 'subcost', 'subcost_@Model.CostEstimateSpendID')">
                <span class="fa fa-plus-square"></span>
            </a>
        }
        @if (Model.ListChildSpend != null && Model.ListChildSpend.Any() || string.IsNullOrWhiteSpace(parentid))
        {
            <b>@Model.SpendItemTitle</b>
        }
        else
        {
            <text>@Model.SpendItemTitle</text>
        }
    </td>
    <td style="vertical-align:middle">
        @if (Model.ListChildSpend != null && Model.ListChildSpend.Any() || string.IsNullOrWhiteSpace(parentid))
        {
            <b>@Model.SpendContent</b>
        }
        else
        {
            <text>@Model.SpendContent</text>
        }
    </td>
    @for (int year = startYear; year <= endYear; year++)
    {
        CostEstimateDetailModel cost = Model.ListDetail == null ? null : Model.ListDetail.Where(x => x.PlanYear == year).FirstOrDefault();
        if (cost == null)
        {
            @Html.Partial("_ListYearCost", new CostEstimateDetailModel());
        }
        else
        {
            if(Model.ListChildSpend != null && Model.ListChildSpend.Any())
            {
                cost.HasChild = true;
            }
            @Html.Partial("_ListYearCost", cost);
            des = cost.Description;
        }
    }
    <td style="text-align:center; vertical-align:middle">
        <input type="text" class="currency form-control input-sm text-only-view" name="SumTotalBudget" readonly="readonly" value="@Model.TotalPrice" style="text-align:right">
    </td>
    <td style="text-align:center; vertical-align:middle">
        <textarea stystyle="text-align:right;" name="ArrDesc" class="form-control input-sm">@des</textarea>
    </td>
</tr>
@if (Model.ListChildSpend != null && Model.ListChildSpend.Any())
{
    foreach (CostEstimateSpendModel item in Model.ListChildSpend)
    {
        @Html.Partial("_ListSubCost", item);
    }
}

IInterface/Views/CostEstimate/_ListSubCostInsert.cshtml
@using IInterface.Models;
@{
    List<CostEstimateSpendModel> listSubSpendItem = ViewData["listSubSpendItem"] as List<CostEstimateSpendModel>;
}

@foreach(CostEstimateSpendModel item in listSubSpendItem)
{
    @Html.Partial("_ListSubCost", item)
}

IInterface/Views/CostEstimate/_ListYearCost.cshtml
@using IInterface.Models;
@model CostEstimateDetailModel
@{
    long subCostID = Model == null ? 0 : Model.CostEstimateDetailID;
    double? TotalPrice = Model == null ? null : Model.TotalMoney;
    bool hasChild = Model == null ? false : Model.HasChild;
    string sReadOnly = hasChild ? "readonly" : "";
    string textView = hasChild ? " text-only-view" : " ";
}
<td style="text-align:center; vertical-align: middle">
    <input type="hidden" name="SubCostID" value="@subCostID" />
    <input type="text" name="TotalPrice" year="@Model.PlanYear" @sReadOnly value="@TotalPrice" onblur="sumMoney(this)" class="currency form-control input-sm @textView" style="text-align:right;" />
</td>