IInterface/Controllers/MissionController.cs
using IInterface.Common;
using IInterface.Models;
using IModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IInterface.Filter;

namespace IInterface.Controllers
{
    public class MissionController : Controller
    {
        // GET: Mission
        private readonly Entities _context = new Entities();
        // GET: Target
        [BreadCrumb(ControllerName = "Nhiệm vụ", ActionName = "Nhiệm vụ", AreaName = "Danh mục")]
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult Search(string MissionCodeSearch = null, string MissionNameSearch = null, int page = 1)
        {
            UserInfo objUser = SessionManager.GetUserInfo();
            IQueryable<MissionModel> IQSearch =
                from x in this._context.Mission
                where x.Status != Constants.IS_NOT_ACTIVE
                select new MissionModel
                {
                    MissionCode = x.MissionCode,
                    MissionName = x.MissionName,
                    CreateTime = x.CreateTime,
                    Creator = x.Creator,
                    Status = x.Status,
                    MissionContent = x.MissionContent,
                    MissionID = x.MissionID
                };
            if (!string.IsNullOrWhiteSpace(MissionCodeSearch))
            {
                IQSearch = IQSearch.Where(x => x.MissionCode.ToLower().Contains(MissionCodeSearch.Trim().ToLower()));
            }
            if (!string.IsNullOrWhiteSpace(MissionNameSearch))
            {
                IQSearch = IQSearch.Where(x => x.MissionName.ToLower().Contains(MissionNameSearch.Trim().ToLower()));
            }


            Paginate<MissionModel> paginate = new Paginate<MissionModel>();
            paginate.PageSize = Constants.PAGE_SIZE;
            paginate.List = IQSearch.OrderBy(x => x.MissionCode).Skip((page - 1) * Constants.PAGE_SIZE).Take(Constants.PAGE_SIZE).ToList();
            paginate.Count = IQSearch.Count();
            ViewData["listMission"] = paginate;
            return PartialView("_ListResult");
        }
        public PartialViewResult PrepareAddOrEdit(int? id)
        {
            MissionModel model = new MissionModel();

            if (id.HasValue && id.Value > 0)
            {
                model = this._context.Mission
                    .Where(x => x.MissionID == id && x.Status != Constants.IS_NOT_ACTIVE)
                    .Select(x => new MissionModel
                    {
                        MissionCode = x.MissionCode,
                        MissionName = x.MissionName,
                        CreateTime = x.CreateTime,
                        Creator = x.Creator,
                        Status = x.Status,
                        MissionContent = x.MissionContent,
                        MissionID = x.MissionID
                    })
                    .FirstOrDefault();
                if (model == null)
                {
                    throw new BusinessException("Không tồn tại nhiệm vụ đã chọn");
                }
                else
                {
                    ViewBag.LstStatus = Utils.GetStatusLst();
                }
            }
            return PartialView("_AddOrEdit", model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Save(MissionModel model)
        {
            UserInfo user = SessionManager.GetUserInfo();
            string msg;
            if (ModelState.IsValid)
            {
                if (model.MissionID > 0)
                {
                    Mission entity = this._context.Mission.FirstOrDefault(x => x.MissionID == model.MissionID && x.Status == Constants.IS_ACTIVE);
                    if (entity == null)
                    {
                        throw new BusinessException("Không tồn tại nhiệm vụ đã chọn");
                    }
                    model.Creator = entity.Creator;
                    model.UpdateEntity(entity);
                    msg = "Cập nhật thành công";
                }
                else
                {
                    Mission entity = model.ToEntity(SessionManager.GetUserInfo().UserName);
                    entity.CreateTime = DateTime.Now;
                    entity.Status = 1;
                    entity.Creator = user != null ? user.UserName : "";
                    this._context.Mission.Add(entity);
                    msg = "Thêm mới thành công";

                }
                this._context.SaveChanges();
                return Json(msg, JsonRequestBehavior.AllowGet);
            }
            else
            {
                throw new BusinessException("Dữ liệu không hợp lệ");
            }

        }
        public JsonResult Delete(int id)
        {
            Mission obj = _context.Mission.Find(id);
            if (obj == null)
            {
                throw new BusinessException("Không tồn tại nhiệm vụ đã chọn");
            }

            _context.Mission.Remove(obj);
            this._context.SaveChanges();
            return Json("Xóa nhiệm vụ thành công", JsonRequestBehavior.AllowGet);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
        
    }
}

IInterface/Views/Mission/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-header with-border">
                @using (Ajax.BeginForm("Search", "Mission", new AjaxOptions
                {
                    HttpMethod = "get",
                    UpdateTargetId = "divGridMission"
                }, new { id = "frmSearch", @class = "form-horizontal" }))
                {
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                @Html.Label("Mã nhiệm vụ", new { @class = "control-label col-md-5" })
                                <div class="col-md-7">
                                    <input id="MissionCodeSearch" name="MissionCodeSearch" class="form-control" placeholder="Mã nhiệm vụ" type="text" />
                                </div>
                            </div>
                        </div>
                        <div class="col-md-8">
                            <div class="form-group">
                                @Html.Label("Tên nhiệm vụ", new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    <div class="input-group with-border">
                                        <input id="MissionNameSearch" name="MissionNameSearch" class="form-control" placeholder="Tên nhiệm vụ" type="text" />
                                        <span class="input-group-btn">
                                            <button class="btn btn-default" type="submit"> <i class="fa fa-search"></i> Tìm kiếm</button>
                                            <button class="btn btn-success" type="button" data-toggle="modal" data-target="#modal-AddOrEdit" onclick="PrepareAddOrEdit(-1)"><i class="fa fa-plus"></i> Thêm mới</button>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="box-body">
                <br />
                <div class="col-lg-12" id="divGridMission">

                </div>
            </div>
        </div>
    </div>
</div>
<div id="modal-AddOrEdit" class="modal fade" Period="dialog"></div>
<script>
    $(document).ready(function () {
        Search();
    });
    function Search() {
        $("#frmSearch").submit();
    }

    function PrepareAddOrEdit(id) {
        $.ajax({
            type: "POST",
            url: '@Url.Action("PrepareAddOrEdit", "Mission")',
            data: {
                'id': id
            },
            success: function (result) {
                $("#modal-AddOrEdit").html(result);
            },
            error: function (xhr) {
                CommonJS.alert(xhr.responseText);
            }
        });
    }
</script>

IInterface/Views/Mission/_AddOrEdit.cshtml
@using IInterface.Models
@model MissionModel
@{
    List<SelectListItem> lstStatus = new List<SelectListItem>();
    if (ViewBag.LstStatus != null)
    {
        lstStatus = ViewBag.LstStatus as List<SelectListItem>;
    }
}
@using (Ajax.BeginForm("Save", "Mission", new AjaxOptions()
{
    HttpMethod = "post",
    OnBegin = "onBegin",
    OnSuccess = "onSuccess",
    OnFailure = "onFail"
}, new { id = "frmCreateOrEdit" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                @if (Model != null && Model.MissionID > 0)
                {
                    @Html.HiddenFor(model => model.MissionID)
                    <h4 class="modal-title">Cập nhật nhiệm vụ</h4>
                }
                else
                {
                    <h4 class="modal-title">Thêm mới nhiệm vụ</h4>
                }

            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    <div class="form-group">
                        @Html.LabelFor(model => model.MissionCode, new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.TextBoxFor(model => model.MissionCode, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MissionCode)
                        </div>
                        @Html.LabelFor(model => model.MissionName, new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.TextBoxFor(model => model.MissionName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MissionName)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.MissionContent, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.MissionContent, new { @class = "form-control", @rows = 10 })
                            @Html.ValidationMessageFor(model => model.MissionContent)
                        </div>
                    </div>
                    @if (Model != null && Model.MissionID > 0)
                    {
                        @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Status, lstStatus, new { @class = "select2", @style = "float:left; width: 100%" })
                        </div>
                    }
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o"></i> Lưu</button>
                <button type="button" data-dismiss="modal" class="btn btn-default"><i class="fa fa-ban"></i> Hủy</button>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $.validator.unobtrusive.adapters.add('isgreater', ['otherproperty', 'ownerproperty'], function (options) {
        options.rules['isgreater'] = { otherproperty: options.params.otherproperty, ownerproperty: options.params.ownerproperty };
        options.messages['isgreater'] = options.message;
    });

    $.validator.addMethod("isgreater", function (value, element, param) {
        var ownerId = element.id;
        var otherid = param.otherproperty;
        if (ownerId !== param.ownerproperty) {
            otherid = ownerId.substr(0, ownerId.length - param.ownerproperty.length) + otherid;
        }
        var otherProp = $('#' + otherid);
        if (otherProp.val() != '') {
            var StartDate = new Date(moment(otherProp.val(), 'DD/MM/YYYY'));

            var Enddate = new Date(moment(value, 'DD/MM/YYYY'));
            if (StartDate != '') {
                return Enddate >= StartDate;
            }
        }
        return true;
    });

    $(document).ready(function () {
        $('select').select2();
        $.validator.unobtrusive.parse("#frmCreateOrEdit");
    });

    function onBegin() {
        if ($("#frmCreateOrEdit").valid()) {
            return true;
        } else {
            return false;
        }
    }

    function onSuccess(msg) {
        CommonJS.alert(msg);
        Search();
    }

    function onFail(xhr) {
        CommonJS.alert(xhr.responseText);
    }
</script>

IInterface/Views/Mission/_ListResult.cshtml
@using IInterface.Common;
@using IInterface.Models;
@{
    Paginate<MissionModel> paginate = ViewData["listMission"] as Paginate<MissionModel>;
    var grid = new WebGrid(
                          rowsPerPage: paginate.PageSize,
                          canPage: true,
                          canSort: false,
                          ajaxUpdateContainerId: "divGridMission"
                          );

    grid.Bind(paginate.List,
    autoSortAndPage: false,
    rowCount: paginate.Count);
    grid.Pager(WebGridPagerModes.All);
}
<style>
    .w30 {
        width: 30% !important;
    }
</style>
@{
    if (paginate.Count > 0)
    {
        var gridColumns = new List<WebGridColumn>();
        gridColumns.Add(grid.Column("MissionCode", "Mã nhiệm vụ"));
        gridColumns.Add(grid.Column("MissionName", "Tên nhiệm vụ", style: "w30"));
        gridColumns.Add(grid.Column("MissionContent", "Nội dung"));
        gridColumns.Add(grid.Column("Creator", "Người tạo"));
        gridColumns.Add(grid.Column("Ngày tạo", format: (item) => string.Format("{0:dd/MM/yyyy}", item.CreateTime)));
        gridColumns.Add(grid.Column("Status", "Trạng thái", format: @<text>
        @if (item.Status == Constants.IS_ACTIVE)
        {
            <label class="label label-success">Hiệu lực</label>
        }
        else
        {
            <label class="label label-default">Hết hiệu lực</label>
        }
        </text>));
        gridColumns.Add(grid.Column(header: "", format: @<text>
            <a href="javascript:void(0)" onclick="prepareEdit(@item.MissionID)" class="btn btn-xs btn-primary" title="Sửa nhiệm vụ"><i class="fa fa-edit"></i> Sửa</a>
            <a href="javascript:void(0)" onclick="deleteMision(@item.MissionID)" class="btn btn-xs btn-danger" title="Xóa nhiệm vụ"><i class="fa fa-trash-o"></i> Xóa</a>
        </text>));
        @grid.GetHtml(htmlAttributes: new { id = "divGridMission" },
                                      fillEmptyRows: false,
                                      tableStyle: "table table-hover table-striped",
                                      footerStyle: "table-pager",
                                      alternatingRowStyle: "altRow",
                                      selectedRowStyle: "selectRow",
                                      mode: WebGridPagerModes.All,
                                      columns: gridColumns)
    }
    else
    {
        <div style="color:red; margin-left:10px;">
            Không có nhiệm vụ nào
        </div>
    }
}
<script type="text/javascript">
    function deleteMision(id) {
        if (!confirm("Bạn có chắc chắn muốn xóa nhiệm vụ?")) {
            return;
        }
        $.ajax({
            type: "POST",
            url: '@Url.Action("Delete", "Mission")',
            data: { 'id': id },
            success: function (data) {
                CommonJS.alert(data);
                Search();
            },
            error: function (xhr) {
                CommonJS.alert(xhr.responseText);
            }
        });
    }

    function prepareEdit(id) {
        $.ajax({
            type: "POST",
            url: '@Url.Action("PrepareAddOrEdit", "Mission")',
            data: {
                'id': id
            },
            success: function (result) {
                $("#modal-AddOrEdit").html(result);
                $("#modal-AddOrEdit").modal("show");
            },
            error: function (xhr) {
                CommonJS.alert(xhr.responseText);
            }
        });
    }

</script>