IInterface/Controllers/ActionController.cs
using IInterface.Common;
using IInterface.Models;
using IModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using IInterface.Filter;
using UserInfo = IInterface.Common.UserInfo;

namespace IInterface.Controllers
{
    public class ActionController : Controller
    {
        // GET: Action
        private readonly Entities _context = new Entities();

        /// <summary>
        /// 
        /// </summary>
        /// <param name="type">type sub or main</param>
        /// <returns></returns>
        [BreadCrumb(ControllerName = "Hoạt động", AreaName = "Hoạt động")]
        public ActionResult Index(int? type)
        {
            ViewData["typeDept"] = type;
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="SearchCode"></param>
        /// <param name="SearchContent"></param>
        /// <param name="typeDept">sub or main</param>
        /// <param name="page"></param>
        /// <returns></returns>
        public PartialViewResult Search(string SearchCode = null, string SearchContent = null, int? typeDept = 0, int TargetID = 0, int page = 1)
        {
            UserInfo objUser = SessionManager.GetUserInfo();

            IQueryable<MainActionModel> IQSearch =
                from x in this._context.MainAction
                join y in _context.Target on x.TargetID equals y.TargetID
                where x.Status != Constants.IS_NOT_ACTIVE
                && x.Type == typeDept
                && (TargetID == 0 || y.TargetID == TargetID)
                select new MainActionModel
                {
                    TypeFor = x.Type,
                    MainActionID = x.MainActionID,
                    MissionID = x.MissionID,
                    ParentID = x.ParentID,
                    Status = x.Status,
                    TargetID = x.TargetID,
                    ActionCode = x.ActionCode,
                    ParentName = _context.MainAction.FirstOrDefault(o => o.MainActionID == x.ParentID).ActionCode,
                    TargetName = y.TargetTitle,
                    ActionContent = x.ActionContent,
                    CrateUser = x.CrateUser,
                    CreatDate = x.CreatDate.Value,
                    Level = x.Level
                };

            if (!string.IsNullOrWhiteSpace(SearchContent))
            {
                IQSearch = IQSearch.Where(x => x.ActionContent.ToLower().Contains(SearchContent.Trim().ToLower()));
            }
            if (!string.IsNullOrWhiteSpace(SearchCode))
            {
                IQSearch = IQSearch.Where(x => x.ActionCode.ToLower().Contains(SearchCode.Trim().ToLower()));
            }

            Paginate<MainActionModel> paginate = new Paginate<MainActionModel>
            {
                PageSize = Constants.PAGE_SIZE,
                List = IQSearch.OrderBy(o => o.TargetID).ThenBy(o => o.ActionCode).Skip((page - 1) * Constants.PAGE_SIZE).Take(Constants.PAGE_SIZE).ToList(),
                Count = IQSearch.Count()
            };
            ViewData["listResult"] = paginate;
            return PartialView("_LstResult");
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <param name="typeDept">sub or main</param>
        /// <param name="type">hành động thêm mới, sửa, thêm con</param>
        /// <returns></returns>
        public PartialViewResult PrepareAddOrEdit(int? id, int? typeDept, int? type)
        {
            var model = new MainActionModel();

            var listTarget = GetListTarget(typeDept).ToList();
            ViewData["listTarget"] = listTarget;
            ViewData["ListMission"] = GetListMission();
            if (type == Constants.ACTION_ADD_NEW)
            {
                model.TypeFor = typeDept;
                model.ActionType = type;
            }

            if (type == Constants.ACTION_ADD_CHILD)
            {
                var parent = _context.MainAction.Find(id);
                if (parent != null)
                {
                    var count = _context.MainAction.Count(o => o.ParentID == parent.MainActionID) + 1;
                    model.ParentID = id;
                    model.ActionCode = parent.ActionCode + "." + count;
                    model.ParentName = parent.ActionContent;
                    model.TargetID = parent.TargetID;
                    model.MissionID = parent.MissionID;
                    model.TypeFor = parent.Type;
                    model.ActionType = type;
                }
                else
                {
                    throw new BusinessException("Hoạt động cha không hợp lệ");
                }
            }

            var listAddedDeptID = new List<int>();
            var listAddedDeptType = new List<int>();
            if (type == Constants.ACTION_EDIT)
            {
                model = this._context.MainAction
                      .Where(x => x.MainActionID == id && x.Status != Constants.IS_NOT_ACTIVE)
                      .Select(x => new MainActionModel
                      {
                          TypeFor = x.Type,
                          MainActionID = x.MainActionID,
                          MissionID = x.MissionID,
                          ParentID = x.ParentID,
                          ParentName = _context.MainAction.FirstOrDefault(o => o.MainActionID == x.ParentID).ActionContent,
                          Status = x.Status,
                          TargetID = x.TargetID,
                          ActionCode = x.ActionCode,
                          ActionContent = x.ActionContent,
                          CrateUser = x.CrateUser,
                          CreatDate = x.CreatDate.Value,
                          ActionType = type,
                          IsOther = (x.IsOther == Constants.IS_ACTIVE)
                      }).FirstOrDefault();

                if (model == null)
                {
                    throw new BusinessException("Không tồn tại hoạt động đã chọn");
                }
                listAddedDeptID.AddRange(_context.MappingActionDepartment.Where(x => x.MainActionID == model.MainActionID && x.DepartmentID != null)
                    .Select(x => x.DepartmentID.Value).ToList());
                listAddedDeptType.AddRange(_context.MappingActionDepartment.Where(x => x.MainActionID == model.MainActionID)
                    .Select(x => x.DepartmentType).ToList());
            }
            if (model.TargetID > 0)
            {
                ViewData["listParent"] = GetListParent(model.TargetID, model.TypeFor);
            }
            else
            {
                ViewData["listParent"] = GetListParent(Convert.ToInt32(listTarget[0].Value), model.TypeFor);
            }
            model.listDeptID = listAddedDeptID.ToArray();
            model.DeptType = listAddedDeptType.ToArray();
            return PartialView("_AddOrEdit", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Save(MainActionModel model)
        {
            if (ModelState.IsValid)
            {
                string msg = null;
                MainAction entity = null;
                if (model.ActionType == Constants.ACTION_EDIT)
                {
                    entity = this._context.MainAction.FirstOrDefault(x => x.MainActionID == model.MainActionID &&
                                                                     x.Status == Constants.IS_ACTIVE);
                    if (entity == null)
                    {
                        throw new BusinessException("Không tồn tại hoạt động đã chọn");
                    }
                    model.UpdateEntity(entity);

                    var listDept = _context.MappingActionDepartment.Where(x => x.MainActionID == entity.MainActionID).ToList();
                    _context.MappingActionDepartment.RemoveRange(listDept);
                    msg = "Cập nhật thành công";
                }
                else
                {
                    var parent = _context.MainAction.Find(model.ParentID);
                    if (parent != null)
                    {
                        model.Level = parent.Level == null ? 1 : parent.Level + 1;
                        model.MissionID = parent.MissionID;
                    }

                    model.CreatDate = DateTime.Now;
                    model.Status = Constants.IS_ACTIVE;

                    entity = model.ToEntity(SessionManager.GetUserInfo().UserName);
                    entity.MissionID = model.MissionID;
                    this._context.MainAction.Add(entity);
                    msg = "Thêm mới thành công";
                }
                if (model.TypeFor == Constants.SUB_TYPE && model.IsOther)
                {
                    var query = _context.MainAction.Where(x => x.IsOther == Constants.IS_ACTIVE);
                    if (model.ActionType == Constants.ACTION_EDIT)
                    {
                        query = query.Where(x => x.MainActionID != model.MainActionID);
                    }
                    var otherAction = query.FirstOrDefault();
                    if (otherAction != null)
                    {
                        throw new BusinessException("Đã có hoạt động khác với mã '" + otherAction.ActionCode + "' và nội dung '" + otherAction.ActionContent + "'");
                    }
                }
                _context.SaveChanges();
                if (entity.Type != Constants.SUB_TYPE && model.DeptType != null && model.DeptType.Any())
                {
                    var listDept = new List<Department>();
                    if (model.listDeptID != null && model.listDeptID.Any())
                    {
                        listDept = _context.Department.Where(x => x.Status == Constants.IS_ACTIVE && model.listDeptID.Contains(x.DepartmentID)).ToList();
                    }

IInterface/Views/Action/Index.cshtml
@using IInterface.Common
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int typeDept = (int)ViewData["typeDept"];
}
<div class="box">
    <div class="box-header">
        @if (typeDept == Constants.MAIN_TYPE)
        {
            <h4 class="box-title">Hoạt động quỹ</h4>
        }
        else
        {
            <h4 class="box-title">Hoạt động đơn vị</h4>
        }
    </div>
    <div class="box-body">
        @using (Ajax.BeginForm("Search", "Action", new AjaxOptions
        {
            HttpMethod = "get",
            UpdateTargetId = "divResult"
        }, new { id = "frmSearch" }))
        {
            <div class="form-horizontal">
                <input type="hidden" name="typeDept" id="typeDept" value="@typeDept" />
                @if (typeDept != Constants.MAIN_TYPE)
                {
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label col-md-3"> Loại đơn vị</label>
                                <div class="col-md-9">
                                    @Html.DropDownList("DeptType", Utils.GetDepartmentType(), htmlAttributes: new { @class = "form-control", style = "width: 100%" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="control-label col-md-3"> Mục tiêu</label>
                                <div class="col-md-9">
                                    @Html.DropDownList("TargetID", new List<SelectListItem>(), htmlAttributes: new { @class = "form-control", style = "width: 100%" })
                                </div>
                            </div>
                        </div>
                    </div>
                }
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.Label("Mã hoạt động", new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                <input id="SearchCode" name="SearchCode" class="form-control" placeholder="Mã hoạt động" type="text" />
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            @Html.Label("Nội dung", new { @class = "control-label col-md-3" })
                            <div class="col-md-9">
                                <div class="input-group with-border">
                                    <input id="SearchContent" name="SearchContent" class="form-control" placeholder="Nội dung hoạt động" type="text" />
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="submit"> <i class="fa fa-search"></i> Tìm kiếm</button>
                                        <button class="btn btn-success" type="button" data-toggle="modal" data-target="#modal-AddOrEdit" onclick="PrepareAddOrEdit(-1, @Constants.ACTION_ADD_NEW)"><i class="fa fa-plus"></i> Thêm mới</button>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<div class="box box-solid">
    <div class="box-body" id="divResult">
    </div>
</div>
<div id="modal-AddOrEdit" class="modal fade" Period="dialog"></div>
<div id="modal-add-mappingAction" class="modal fade" role="dialog"></div>
<script>
    $(document).ready(function () {
        Search();
        $(function () {
            $('#frmSearch #TargetID').select2({
                placeholder: 'Lựa chọn mục tiêu...'
            });
            $('#frmSearch #TargetID').select2('val', '');
            $('#frmSearch #DeptType').select2();
            $("#frmSearch #DeptType").change(function () {
                var type = $(this).val();
                Search();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("GetLstTargetByDept", "Target")',
                    data: { deptType: type },
                    success: function (data) {
                        var select = $("#frmSearch #TargetID");
                        select.empty();
                        select.append($('<option/>', {
                            value: 0,
                            text: "-- Chọn --"
                        }));
                        $.each(data, function (index, itemData) {
                            select.append($('<option/>', {
                                value: itemData.Value,
                                text: itemData.Text
                            }));
                        });
                    },
                    error: function (xhr) {
                        CommonJS.alert(xhr.responseText);
                    }
                });
            });
        });
    });
    function Search() {
        $("#frmSearch").submit();
    }

    function AddAction(id) {
        $.ajax({
            type: "POST",
            url: '@Url.Action("LoadMappingAction", "Action")',
            data: {
                'id': id
            },
            success: function (result) {
                $("#modal-add-mappingAction").html(result);
                $("#modal-add-mappingAction").modal("show");
                $("#hidTargetID").val(id);
            },
            error: function (xhr) {
                CommonJS.alert(xhr.responseText);
            }
        });
    }

    function ReloadAction(id) {
        $.ajax({
            type: "POST",
            url: '@Url.Action("LoadMappingAction", "Action")',
            data: {
                'id': id
            },
            success: function (result) {
                $("#modal-add-mappingAction").html(result);
                $("#hidTargetID").val(id);
            },
            error: function (xhr) {
                CommonJS.alert(xhr.responseText);
            }
        });
    }
</script>

IInterface/Views/Action/_AddOrEdit.cshtml
@using IInterface.Common
@model IInterface.Models.MainActionModel
@{
    List<SelectListItem> listTarget = ViewData["listTarget"] as List<SelectListItem>;
    List<SelectListItem> listParent = ViewData["listParent"] as List<SelectListItem>;
    List<SelectListItem> listMission = ViewData["ListMission"] as List<SelectListItem>;
    listMission.Insert(0, new SelectListItem { Value = "", Text = "--Nhiệm vụ--" });
    List<SelectListItem> listDeptType = Utils.GetDepartmentType().Where(x => !string.IsNullOrWhiteSpace(x.Value) && !x.Value.Equals(Constants.DEPT_TYPE_PBQUY.ToString())).ToList();
    int id = Model != null && Model.ActionType == Constants.ACTION_EDIT ? Model.MainActionID : 0;
}

@using (Ajax.BeginForm("Save", "Action", new AjaxOptions()
{
    HttpMethod = "post",
    OnBegin = "onBegin",
    OnSuccess = "onSuccess",
    OnFailure = "onFail"
}, new { id = "frmCreateOrEdit" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                @if (Model != null && Model.ActionType == Constants.ACTION_EDIT)
                {
                    @Html.HiddenFor(model => model.MainActionID)
                    <h4 class="modal-title">Cập nhật hoạt động</h4>
                }
                else
                {
                    <h4 class="modal-title">Thêm mới hoạt động</h4>
                }

            </div>
            <div class="modal-body">
                <div class="form-horizontal">
                    @Html.HiddenFor(model => model.TypeFor)
                    @Html.HiddenFor(model => model.ActionType)
                    <div class="form-group">
                        @Html.LabelFor(model => model.ActionCode, htmlAttributes: new { @class = "control-label col-md-2" })
                        @if (Model != null && Model.TypeFor.GetValueOrDefault() == Constants.MAIN_TYPE)
                        {
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.ActionCode, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ActionCode)
                            </div>
                        }
                        else
                        {
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.ActionCode, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ActionCode)
                            </div>
                            <div class="col-md-4 ">
                                <label>@Html.CheckBoxFor(x => x.IsOther) &nbsp;Hoạt động khác</label>
                            </div>
                        }
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.ActionContent, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.ActionContent, new { @class = "form-control", @rows = 3 })
                            @Html.ValidationMessageFor(model => model.ActionContent)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.TargetID, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.TargetID, listTarget, new { @class = "select2", @style = "float:left; width: 100%", @id = "TargetId" })
                            @*@Html.ValidationMessageFor(model => model.Status)*@
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.ParentID, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.ParentID, listParent, new { @class = "select2", @style = "float:left; width: 100%", @id = "ParentId" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.Label("", "Nhiệm vụ", new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.MissionID, listMission, new { @class = "select2", @style = "float:left; width: 100%", @id = "missionId" })
                        </div>
                    </div>
                    @if (Model != null && Model.TypeFor.GetValueOrDefault() == Constants.MAIN_TYPE)
                    {
                        <div class="form-group">
                            @Html.Label("", "Loại đơn vị", new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.ListBoxFor(model => model.DeptType, listDeptType, new { multiple = "multiple", @class = "js-example-basic-single form-control", @style = "float:left; width: 100%", @id = "DeptType" })
                            </div>
                        </div>
                        <div class="form-group" id="divMappingDept">
                        </div>
                    }
                    @Html.HiddenFor(model => model.Status)
                </div>

            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success"><i class="fa fa-floppy-o"></i> Lưu</button>
                <button type="button" data-dismiss="modal" class="btn btn-default"><i class="fa fa-ban"></i> Hủy</button>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $(document).ready(function () {
        $('select').select2();
        $.validator.unobtrusive.parse("#frmCreateOrEdit");
        var deptType = $("#frmCreateOrEdit #DeptType").val();
        getDept(deptType);
        $("#frmCreateOrEdit #TargetId").change(function () {
            var targetId = $(this).val();
            var deptType = $("#TypeFor").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("LoadListParentAction", "Action")',
                data: { targetId: targetId ,deptType:deptType},
                success: function (data) {
                    var select = $("#frmCreateOrEdit #ParentId");
                    select.empty();
                    $.each(data, function (index, itemData) {
                        select.append($('<option/>', {
                            value: itemData.Value,
                            text: itemData.Text
                        }));
                    });
                },
                error: function (xhr) {
                    CommonJS.alert(xhr.responseText);
                }
            });
        });

        $("#DeptType").change(function () {
            var deptType = $(this).val();
            getDept(deptType);
        });
    });

    function getDept(deptType) {
        if (deptType != "") {
            $.ajax({
                type: "POST",
                url: '@Url.Action("LoadListDept", "Action")',
                data: { "deptType": deptType, 'id': @id },
                success: function (data) {
                    $("#divMappingDept").html(data);
                },
                error: function (xhr) {
                    CommonJS.alert(xhr.responseText);
                }
            });
        } else {
            var select = $("#frmCreateOrEdit #DeptID");
            select.empty();
        }
    }

    function onBegin() {
        if ($("#frmCreateOrEdit").valid()) {
            return true;
        } else {
            return false;
        }
    }

    function onSuccess(msg) {
        CommonJS.alert(msg);
        $('#modal-AddOrEdit').modal('toggle');
        Search();
    }

    function onFail(xhr) {
        CommonJS.alert(xhr.responseText);
    }
</script>

IInterface/Views/Action/_LstResult.cshtml
@using IInterface.Common;
@using IInterface.Models;
@{
    Paginate<MainActionModel> paginate = ViewData["listResult"] as Paginate<MainActionModel>;
    var grid = new WebGrid(
                          rowsPerPage: paginate.PageSize,
                          canPage: true,
                          canSort: false,
                          ajaxUpdateContainerId: "divGridResult"
                          );

    grid.Bind(paginate.List,
    autoSortAndPage: false,
    rowCount: paginate.Count);
    grid.Pager(WebGridPagerModes.All);
}
<style>
    .ContentColumn {
        width: 40%;
    }

    .CodeColumn {
        width: 10px;
    }

    .w12 {
        width: 15px !important;
    }

    .stable-action {
        vertical-align: middle !important;
    }
</style>
@{
    if (paginate.Count > 0)
    {
        var gridColumns = new List<WebGridColumn>();
        gridColumns.Add(grid.Column("TargetName", "Mục tiêu"));
        gridColumns.Add(grid.Column("ActionCode", "Mã HĐ", style: "w12"));
        gridColumns.Add(grid.Column("ActionContent", "Nội dung hoạt động", format: @<text>

    @for (int i = 1; i <= @item.Level; i++)
    {
        <label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
    }
    @if (@item.Level > 0 && @item.ParentID != null)
    {
        <label>- </label>
    }
    @item.ActionContent
        </text>, style: "ContentColumn"));
 gridColumns.Add(grid.Column("ParentName", "Hoạt động cha"));
 gridColumns.Add(grid.Column(header: "Cấp áp dụng", format: @<text>
    @if (item.TypeFor == Constants.MAIN_TYPE)
    {
        <span class="label label-primary">Quỹ</span>

    }
    else
    {
        <span class="label label-success">Đơn vị</span>
    }
</text>));
gridColumns.Add(grid.Column("Ngày tạo", format: (item) => string.Format("{0:dd/MM/yyyy}", item.CreatDate)));
gridColumns.Add(grid.Column(header: "", format: @<text>
    <a href="javascript:void(0)" onclick="PrepareAddOrEdit(@item.MainActionID,@Constants.ACTION_ADD_CHILD)" data-toggle="modal" data-target="#modal-AddOrEdit" class="btn btn-xs btn-success" title="Thêm hoạt động nhỏ"><i class="fa fa-plus"></i></a>
    <a href="javascript:void(0)" onclick="PrepareAddOrEdit(@item.MainActionID,@Constants.ACTION_EDIT)" data-toggle="modal" data-target="#modal-AddOrEdit" class="btn btn-xs btn-primary" title="Sửa thông tin"><i class="fa fa-edit"></i></a>
    <a href="javascript:void(0)" onclick="deleteAction(@item.MainActionID)" class="btn btn-xs btn-danger" title="Xóa thông tin"><i class="fa fa-trash-o"></i></a>
</text>));

@grid.GetHtml(htmlAttributes: new { id = "divGridResult" },
                              fillEmptyRows: false,
                              tableStyle: "table table-hover table-striped stable-action",
                              footerStyle: "table-pager",
                              alternatingRowStyle: "altRow",
                              selectedRowStyle: "selectRow",
                              mode: WebGridPagerModes.All,
                              columns: gridColumns)

}
else
{
<div style="color:red; margin-left:10px;">
    Không có dữ liệu
</div>
}
}
<script>
    function PrepareAddOrEdit(id, type) {
        var typeDept = $("#typeDept").val();
        $.ajax({
            type: "POST",
            url: '@Url.Action("PrepareAddOrEdit", "Action")',
            data: {
                'id': id,
                'typeDept': typeDept,
                'type': type
            },
            success: function (result) {
                $("#modal-AddOrEdit").html(result);
            },
            error: function (xhr) {
                CommonJS.alert(xhr.responseText);
            }
        });
    }

    function deleteAction(id) {
        if (!confirm("Bạn có chắc chắn muốn xóa hoạt động?")) {
            return;
        }
        $.ajax({
            type: "POST",
            url: '@Url.Action("Delete", "Action")',
            data: { 'id': id },
            success: function (data) {
                CommonJS.alert(data);
                Search();
            },
            error: function (xhr) {
                CommonJS.alert(xhr.responseText);
            }
        });
    }
</script>

IInterface/Views/Action/_listDept.cshtml
@{
    List<SelectListItem> listDept = ViewData["listDept"] as List<SelectListItem>; ;
}
@Html.Label("", "Đơn vị", new { @class = "control-label col-md-2" })
<div class="col-md-10">
    @Html.ListBox("listDeptID", listDept, new { multiple = "multiple", @class = "js-example-basic-single form-control", style = "width:100%", @id = "DeptID" })
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('select').select2();
    });
</script>